import { PlanModel } from './plan.model';

export class ProfileModel {
    constructor(public avatar_url: string,
                public bio: string,
                public blog: string,
                public collaborators: number,
                public company: string,
                public created_at: string,
                public disk_usage: number,
                public email: string,
                public events_url: string,
                public followers: number,
                public followers_url: string,
                public following: number,
                public following_url: string,
                public gists_url: string,
                public gravatar_id: string,
                public hireable: string,
                public html_url: string,
                public id: number,
                public location: string,
                public login: string,
                public name: string,
                public node_id: string,
                public organizations_url: string,
                public owned_private_repos: number,
                public plan: PlanModel,
                public private_gists: number,
                public public_gists: number,
                public public_repos: number,
                public received_events_url: string,
                public repos_url: string,
                public site_admin: boolean,
                public starred_url: string,
                public subscriptions_url: string,
                public total_private_repos: number,
                public two_factor_authentication: boolean,
                public type: string,
                public updated_at: string,
                public url: string) {
    }
}
