import { OwnerModel } from './owner.model';

export class RepoModel {
  public id: number;
  public nodeId: string;
  public name: string;
  public fullName: string;
  public private: boolean;
  public owner: OwnerModel;
  public htmlUrl: string;
  public description: string;
  public fork: boolean;
  public url: string;
  public forksUrl: string;
  public keysUrl: string;
  public collaboratorsUrl: string;
  public teamsUrl: string;
  public hooksUrl: string;
  public issueEventsUrl: string;
  public eventsUrl: string;
  public assigneesUrl: string;
  public branchesUrl: string;
  public tagsUrl: string;
  public blobsUrl: string;
  public gitTagsUrl: string;
  public gitRefsUrl: string;
  public treesUrl: string;
  public statusesUrl: string;
  public languagesUrl: string;
  public stargazersUrl: string;
  public contributorsUrl: string;
  public subscribersUrl: string;
  public subscriptionUrl: string;
  public commitsUrl: string;
  public gitCommitsUrl: string;
  public commentsUrl: string;
  public issueCommentUrl: string;
  public contentsUrl: string;
  public compareUrl: string;
  public mergesUrl: string;
  public archiveUrl: string;
  public downloadsUrl: string;
  public issuesUrl: string;
  public pullsUrl: string;
  public milestonesUrl: string;
  public notificationsUrl: string;
  public labelsUrl: string;
  public releasesUrl: string;
  public deploymentsUrl: string;
  public createdAt: string;
  public updatedAt: string;
  public pushedAt: string;
  public gitUrl: string;
  public sshUrl: string;
  public cloneUrl: string;
  public svnUrl: string;
  public homepage: string;
  public size: number;
  public stargazersCount: number;
  public watchersCount: number;
  public language: string;
  public hasIssues: boolean;
  public hasProjects: boolean;
  public hasDownloads: boolean;
  public hasWiki: boolean;
  public hasPages: boolean;
  public forksCount: number;
  public mirrorUrl: string;
  public archived: boolean;
  public disabled: boolean;
  public openIssuesCount: number;
  public license: string;
  public forks: number;
  public openIssues: number;
  public watchers: number;
  public defaultBranch: string;

  constructor(data: any = {}) {
    this.id = data.id || void 0;
    this.nodeId = data.nodeId || void 0;
    this.name = data.name || void 0;
    this.fullName = data.fullName || void 0;
    this.private = !!data.private;
    this.owner = data.owner && new OwnerModel(data.owner) || void 0;
    this.htmlUrl = data.htmlUrl || void 0;
    this.description = data.description || void 0;
    this.fork = !!data.fork;
    this.url = data.url || void 0;
    this.forksUrl = data.forksUrl || void 0;
    this.keysUrl = data.keysUrl || void 0;
    this.collaboratorsUrl = data.collaboratorsUrl || void 0;
    this.teamsUrl = data.teamsUrl || void 0;
    this.hooksUrl = data.hooksUrl || void 0;
    this.issueEventsUrl = data.issueEventsUrl || void 0;
    this.eventsUrl = data.eventsUrl || void 0;
    this.assigneesUrl = data.assigneesUrl || void 0;
    this.branchesUrl = data.branchesUrl || void 0;
    this.tagsUrl = data.tagsUrl || void 0;
    this.blobsUrl = data.blobsUrl || void 0;
    this.gitTagsUrl = data.gitTagsUrl || void 0;
    this.gitRefsUrl = data.gitRefsUrl || void 0;
    this.treesUrl = data.treesUrl || void 0;
    this.statusesUrl = data.statusesUrl || void 0;
    this.languagesUrl = data.languagesUrl || void 0;
    this.stargazersUrl = data.stargazersUrl || void 0;
    this.contributorsUrl = data.contributorsUrl || void 0;
    this.subscribersUrl = data.subscribersUrl || void 0;
    this.subscriptionUrl = data.subscriptionUrl || void 0;
    this.commitsUrl = data.commitsUrl || void 0;
    this.gitCommitsUrl = data.gitCommitsUrl || void 0;
    this.commentsUrl = data.commentsUrl || void 0;
    this.issueCommentUrl = data.issueCommentUrl || void 0;
    this.contentsUrl = data.contentsUrl || void 0;
    this.compareUrl = data.compareUrl || void 0;
    this.mergesUrl = data.mergesUrl || void 0;
    this.archiveUrl = data.archiveUrl || void 0;
    this.downloadsUrl = data.downloadsUrl || void 0;
    this.issuesUrl = data.issuesUrl || void 0;
    this.pullsUrl = data.pullsUrl || void 0;
    this.milestonesUrl = data.milestonesUrl || void 0;
    this.notificationsUrl = data.notificationsUrl || void 0;
    this.labelsUrl = data.labelsUrl || void 0;
    this.releasesUrl = data.releasesUrl || void 0;
    this.deploymentsUrl = data.deploymentsUrl || void 0;
    this.createdAt = data.createdAt || void 0;
    this.updatedAt = data.updatedAt || void 0;
    this.pushedAt = data.pushedAt || void 0;
    this.gitUrl = data.gitUrl || void 0;
    this.sshUrl = data.sshUrl || void 0;
    this.cloneUrl = data.cloneUrl || void 0;
    this.svnUrl = data.svnUrl || void 0;
    this.homepage = data.homepage || void 0;
    this.size = data.size || void 0;
    this.stargazersCount = data.stargazersCount || void 0;
    this.watchersCount = data.watchersCount || void 0;
    this.language = data.language || void 0;
    this.hasIssues = !!data.hasIssues;
    this.hasProjects = !!data.hasProjects;
    this.hasDownloads = !!data.hasDownloads;
    this.hasWiki = !!data.hasWiki;
    this.hasPages = !!data.hasPages;
    this.forksCount = data.forksCount || void 0;
    this.mirrorUrl = data.mirrorUrl || void 0;
    this.archived = !!data.archived;
    this.disabled = !!data.disabled;
    this.openIssuesCount = data.openIssuesCount || void 0;
    this.license = data.license || void 0;
    this.forks = data.forks || void 0;
    this.openIssues = data.openIssues || void 0;
    this.watchers = data.watchers || void 0;
    this.defaultBranch = data.defaultBranch || void 0;
  }
}




