import { PlanModel } from './plan.model';

export class UserModel {
  public avatarUrl: string;
  public bio: string;
  public blog: string;
  public collaborators: number;
  public company: string;
  public createdAt: string;
  public diskUsage: number;
  public email: string;
  public eventsUrl: string;
  public followers: number;
  public followersUrl: string;
  public following: number;
  public followingUrl: string;
  public gistsUrl: string;
  public gravatarId: string;
  public hireable: string;
  public htmlUrl: string;
  public id: number;
  public location: string;
  public login: string;
  public name: string;
  public nodeId: string;
  public organizationsUrl: string;
  public ownedPrivateRepos: number;
  public plan: PlanModel;
  public privateGists: number;
  public publicGists: number;
  public publicRepos: number;
  public receivedEventsUrl: string;
  public reposUrl: string;
  public siteAdmin: boolean;
  public starredUrl: string;
  public subscriptionsUrl: string;
  public totalPrivateRepos: number;
  public twoFactorAuthentication: boolean;
  public type: string;
  public updatedAt: string;
  public url: string;

  constructor(data: any = {}) {
    this.avatarUrl = data.avatarUrl || void 0;
    this.bio = data.bio || void 0;
    this.blog = data.blog || void 0;
    this.collaborators = data.collaborators || void 0;
    this.company = data.company || void 0;
    this.createdAt = data.createdAt || void 0;
    this.diskUsage = data.diskUsage || void 0;
    this.email = data.email || void 0;
    this.eventsUrl = data.eventsUrl || void 0;
    this.followers = data.followers || void 0;
    this.followersUrl = data.followersUrl || void 0;
    this.following = data.following || void 0;
    this.followingUrl = data.followingUrl || void 0;
    this.gistsUrl = data.gistsUrl || void 0;
    this.gravatarId = data.gravatarId || void 0;
    this.hireable = data.hireable || void 0;
    this.htmlUrl = data.htmlUrl || void 0;
    this.id = data.id || void 0;
    this.location = data.location || void 0;
    this.login = data.login || void 0;
    this.name = data.name || void 0;
    this.nodeId = data.nodeId || void 0;
    this.organizationsUrl = data.organizationsUrl || void 0;
    this.ownedPrivateRepos = data.ownedPrivateRepos || void 0;
    this.plan = data.plan || void 0;
    this.privateGists = data.privateGists || void 0;
    this.publicGists = data.publicGists || void 0;
    this.publicRepos = data.publicRepos || void 0;
    this.receivedEventsUrl = data.receivedEventsUrl || void 0;
    this.reposUrl = data.reposUrl || void 0;
    this.siteAdmin = data.siteAdmin || void 0;
    this.starredUrl = data.starredUrl || void 0;
    this.subscriptionsUrl = data.subscriptionsUrl || void 0;
    this.totalPrivateRepos = data.totalPrivateRepos || void 0;
    this.twoFactorAuthentication = data.twoFactorAuthentication || void 0;
    this.type = data.type || void 0;
    this.updatedAt = data.updatedAt || void 0;
    this.url = data.url || void 0;
  }
}
